### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by sharkcrayon**
Accept whatever you like, throw out whatever you don't!

### CODE REVIEW

**Comment by gavinmcdermott** [comment]
Thanks @sharkcrayon—these look great to me (lgtm)! Merging away!

**Comment by gavinmcdermott** [comment]
**PS @sharkcrayon :**

A random side note for more Git learnings: Because all of these changes are related, you could [squash all of the commits into a single one](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) before making the pr. 

It's been something that's come in handy a few times for me though and just wanted to share. Zero pressure to do it here (I don't do it all the time either), but it can make for a nicer commit history over the long haul when committing to third party projects. 

Also, a small tip on this based on a lesson I learned the hard way back in the day ;) :
- You may want to practice working with interactive rebases / squashes in a project that is your own where you can mess up while figuring things out. These types of actions actually rewrite project history, and if you make them on a branch that other people are working from, it can really create a bad hairball on a distributed team. This is why you usually do all squashes and history rewrites before pushing code to a place where others on the team can pull from it (e.g.: GitHub).

**Comment by sharkcrayon** [comment]
I actually did with some of my commits, but I didn't want to squash them
all together in case you didn't want to accept everything. What's the
balance there? When accepting a pull request do you have the option to just
accept part of it? What do you do if a pull request contains some stuff
that you don't want?

**Comment by gavinmcdermott** [comment]
Great questions—you're already light years ahead of my comments!  

Here's my take:

> ...but I didn't want to squash them all together in case you didn't want to accept everything. What's the balance there?

I find this to be more art than rule :) _as with most programming!_

> When accepting a pull request do you have the option to just accept part of it?

Yep. You can [cherry pick certain commits](http://stackoverflow.com/questions/7217031/github-accept-pull-request-but-only-some-commits) if you only want to accept a select handful of non-breaking changes.

> What do you do if a pull request contains some stuff that you don't want?

I suppose this is up to the team's discretion. Here's a couple (but certainly not all) options:
- The reviewer can make comments and ask for changes. 
- The reviewer can cherry pick some commits and ditch the rest; asking for another cycle on the remaining feature 

Overall, you have lots of freedom with how to handle this.

Anyhow, feel free to let me know if I missed/skipped something!

**Comment by sharkcrayon** [comment]
Cool :)

So I guess if I squashed all the commits into one, then you wouldn't have
the option to cherry pick commits anymore, but you could ask me to revise.

If the PR contains multiple commits (which leaves you with the option to
cherry pick), would it make sense to rebase on your end after accepting the
ones you wanted? Though, thinking about that, I'm imaging issues that might
create. Let me know if any of these are issues that actually occur:
1. does that obfuscate the history of what the accepted pull request
   contributed?
2. does that create a hairball? I wouldn't imagine so, since we're on two
   different repos that aren't trying to share a history in the first place.
3. though maybe it does create a hairball since your original repo is set
   upstream of mine so I can rebase your changes into my repo...

Just curious :) I just started learning about rebasing tonight. Random
aside: the name "interactive rebasing" is badass.

Oh, one other question: I created those changes on a feature branch. Does
the PR contain any branch-related information? I'd imagine not, and I'd
imagine that you also choose on your end what branch to merge the PR
into...is that right?

**Comment by gavinmcdermott** [comment]
Yes. The `interactive rebase` is perhaps _the most_ badass command in the entire programming lexicon.

Regarding the master versions of history, `git log` is what I've always used to show me the 'true' history regardless of cherry picks and other events. From what is expected, the log output should be the current state of all merged features and branches.

Your PR that I merged into `master` was represented in GitHub only under the branch name that you pushed to. So your local branch could be called `feature-foo` and you could push that to branch `feature-bar` on origin, and I'd think that I was merging branch `feature-bar` into the `develop` branch (or whatever). And currently, because we only have a `master` working branch on GitHub right now, I did not have the choice as to where to merge it—and coincidentally neither did you. When there are multiple branches on origin (GitHub), the person opening the the pull request has to choose which branch they're merging into.

**Comment by sharkcrayon** [comment]
Ok! I believe that makes sense. Time and use shall tell.

**Pull request merged**
